### ISSUE TITLE
Support for manifest.json v11 / dbt v1.7

### ISSUE THREAD

**Issue by Erik-vdg** [datnguye/dbterd#61] opened 2023-11-30 19:36 UTC
**Describe the bug**
Similar to #43, dbt manifest.json of version 11 is unable to be parsed by dbterd:
`Error: Could not open file 'manifest.json': File manifest.json is corrupted, please rebuild`

**To Reproduce**
run `dbterd run -mv 11`

**Expected behavior**
Generation of target ERD script

**Desktop (please complete the following information):**

- OS: iOS

**Additional context**
When I upgraded `dbt-artifacts-parser` in my virtualenv to version `0.5.0` I was able to parse the manifest correctly.

**Comment by datnguye** [comment] 2023-12-01 04:31
Thanks @Erik-vdg for raising it!
Yes that's the expected behavior where I tried to [free the top pin](https://github.com/datnguye/dbterd/blob/a0da8c8c19061afef4aaba175aab5a71d01d39ed/pyproject.toml#L32C30-L32C30) of `dbt-artifacts-parser`.

I will try to update the documentation for that when available.
For now, I will call it `won't fix` but keen to hear your feedback on how we can bypass this automatically.

Thanks

Thanks

**Comment by Erik-vdg** [comment] 2023-12-01 16:35
Thanks @datnguye, I appreciate your comment, and I also am really appreciating the dbterd tool.

From my point of view - I was evaluating the dbterd tool before I would recommend it to my coworkers. I encountered the issue with the `dbt-artifacts-parser` library on my own and was able to solve it myself. However, some of my colleagues are not very technical and would not be able to solve this on their own.

I would like to propose two options to improve the user experience. Both are not mutually exclusive:

1. Release a new version of dbterd with the dependency `dbt-artifacts-parser` pinned to `"^0.5"`.
2. Enhance the error message when dbterd encounters a manifest version it does not yet know about, suggesting the user to update their version of `dbt-artifacts-parser`. This is currently emitted when the user runs with the -mv flag, but is not emitted when the user does not provide the -mv flag. I would like the same warning message to be emitted when the -mv flag is not present.

Let me know which option(s) fit in your vision of dbterd. I would be happy to assist by creating a PR for either of these options.

**Comment by datnguye** [comment] 2023-12-02 05:24
Cheers @Erik-vdg and yes you are more than welcome to create a PR for it, can you help please? I will try to review and release it as soon as possible.

Regarding to the 2nd point, I am a bit surprised because I implemented [this message](https://github.com/datnguye/dbterd/blob/84b19e86dc160eb020fc853ea83139c3f5a873c5/dbterd/helpers/file.py#L127) which is similar to your suggestion. But feel free to make it better and centralized.

**Closed** 2023-12-06 01:55 UTC
Labels: enhancement, help wanted
